### ISSUE TITLE
Goal Labels

### ISSUE THREAD

**Issue by aycatakmaz** [mohamedhassanmus/SAMP#1]
First of all, thank you very much for this exciting work! I saw that the motion clips are available on the project website, but I was unable to find the manually annotated goal labels. Are the goal annotations publicly available, or do you plan to make them available in near future?

Thank you very much for your time!

**Comment by mohamedhassanmus** [comment]
Thank you for your interest. The goal labels were done in Unity and will be part of the code release which is not yet out.
