### ISSUE TITLE
About the training details in index selection

### ISSUE THREAD

**Issue by SternenHimmel0299** [mohamedhassanmus/SAMP#4]
Thanks a lot for your great work!
One question about the training code in MotionNet_train.py, line 35-40:
>>
        for i in range(args.L):
            optimizer.zero_grad()
            p = y[:, i, :]
            p_prev = x1[:, i, :]
            I = x2[:, i, :]
So i am assuming that the rollout length is the sequence length which is determined to be 60 in your implemetation.
I am wondering in the encoding stage, why the indices for both previous pose p_prev and next pose p are set to i. Does that mean the i-th pose in p_prev is the corresponding past pose for the i-th pose in p? 

I would appreciate it very much if you could reply to my quesytion. Thank you!

**Comment by mohamedhassanmus** [comment]
Yes. It is exactly as you guessed. The i-th pose in p_prev is the corresponding past pose for the i-th pose in p.

**Comment by SternenHimmel0299** [comment]
Thank you for the kind reply! That helped me a lot.
