### ISSUE TITLE
Is the FD evaluation method available?

### ISSUE THREAD

**Issue by Frank-Dz** [mohamedhassanmus/SAMP#6]
Hi~ Thanks for your great work!
If it is possible to share the FD evaluation method used in the paper?

Thanks!

**Comment by mohamedhassanmus** [comment]
The FD formula can be found in Wikipedia https://en.wikipedia.org/wiki/Fr%C3%A9chet_distance
under As a distance between probability distributions (the FID score)
or this paper https://www.sciencedirect.com/science/article/pii/0047259X8290077X
